name: release

on:
  push:
    branches:
      - main

jobs:

  tag:
    name: Create version tag
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.tag.outputs.changelog }}
      tag: ${{ steps.tag.outputs.new_tag }}
      version: ${{ steps.tag.outputs.new_version }}
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Bump version and tag
        uses: mathieudutour/github-tag-action@v6.1
        id: tag
        with:
          default_bump: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build app archives
    runs-on: ubuntu-latest
    needs:
      - tag
    if: ${{ needs.tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create archive source
        run: |
          mkdir musicxmlplayer
          cp -r appinfo css files img js lib musicxmlplayer/
      - name: Edit version
        run: |
          sed -i 's/<version>0.0.1<\/version>/<version>${{ needs.tag.outputs.version }}<\/version>/' musicxmlplayer/appinfo/info.xml
      - name: Create zip archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: musicxmlplayer-${{ needs.tag.outputs.tag }}.zip
          path: musicxmlplayer
          exclusions: '.git* .eslintrc.yaml .stylelintrc.js composer.json package.json'
      - name: Create tar archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: tar
          filename: musicxmlplayer-${{ needs.tag.outputs.tag }}.tar.gz
          path: musicxmlplayer
          exclusions: '.git* .eslintrc.yaml .stylelintrc.js composer.json package.json'
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: archives
          path: musicxmlplayer-v*
          retention-days: 1

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - tag
      - build
    if: ${{ needs.tag.outputs.new_tag }}
    steps:
      - name: Fetch archives
        uses: actions/download-artifact@v3
        with:
          name: archives
      - name: Create checksums
        run: |
          sha256sum musicxmlplayer-v* | tee musicxmlplayer-${{ needs.tag.outputs.tag }}.sha256
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          name: Release ${{ needs.tag.outputs.version }}
          body: |
            Changes in this release:
            ${{ needs.tag.outputs.changelog }}
          files: musicxmlplayer-v*
